# Created with WinGet Releaser using komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: igoogolx.itun2socks
PackageVersion: 1.28.5
PackageLocale: en-US
Publisher: igoogolx
PublisherUrl: https://github.com/igoogolx
PublisherSupportUrl: https://github.com/igoogolx/itun2socks/issues
PackageName: itun2socks
PackageUrl: https://github.com/igoogolx/itun2socks
License: GPL-3.0
LicenseUrl: https://github.com/igoogolx/itun2socks/blob/HEAD/LICENSE
ShortDescription: tun proxy tool
Tags:
- clash
- shadowsocks
- vpn
ReleaseNotes: |-
  Changelog
  - d43a302 v1.28.5 (#85)
ReleaseNotesUrl: https://github.com/igoogolx/itun2socks/releases/tag/v1.28.5
ManifestType: defaultLocale
ManifestVersion: 1.9.0
